language: python
sudo: false
addons:
  firefox: "61.0"

matrix:
  include:
    - python: "2.7"
      env: TOXENV=docs,lint-py27,code-analysis
    - python: "3.6"
      env: TOXENV=docs,lint-py36
    - python: "2.7"
      env: TOXENV=py27-Plone43
    - python: "2.7"
      env: TOXENV=py27-Plone50
    - python: "2.7"
      env: TOXENV=py27-Plone51
    - python: "2.7"
      env: TOXENV=py27-Plone52
    - python: "3.6"
      env: TOXENV=py36-Plone52
  allow_failures:
    - python: "3.6"
      env: TOXENV=py36-Plone52

cache:
  pip: true
  directories:
    - eggs
    - $HOME/buildout-cache

before_install:
    - mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
    - mkdir $HOME/.buildout
    - echo "[buildout]" > $HOME/.buildout/default.cfg
    - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
    - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
    - echo "extends-cache = $HOME/buildout-cache/extends" >> $HOME/.buildout/default.cfg
    - echo "abi-tag-eggs = true" >> $HOME/.buildout/default.cfg

install:
  - travis_retry pip install -U setuptools pip tox coveralls coverage
  - mkdir bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C bin
  - export PATH=$(pwd)/bin:$PATH

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v

script:
  - travis_retry tox

after_success:
  - coverage combine
  - coveralls
